//
// Created by MightyPork on 2017/08/19.
//

#ifndef ESP_VT100_FIRMWARE_SGR_H
#define ESP_VT100_FIRMWARE_SGR_H

enum SGR_CODES {
	SGR_RESET = 0,
	SGR_BOLD = 1,
	SGR_FAINT = 2,
	SGR_ITALIC = 3,
	SGR_UNDERLINE = 4,
	SGR_BLINK = 5,
	SGR_BLINK_FAST = 6,
	SGR_INVERSE = 7,
	SGR_STRIKE = 9,
	SGR_FRAKTUR = 20,

	SGR_FG_START = 30,
	SGR_FG_END = 37,
	SGR_FG_DEFAULT = 39,

	SGR_BG_START = 40,
	SGR_BG_END = 47,
	SGR_BG_DEFAULT = 49,

	SGR_FG_BRT_START = 90,
	SGR_FG_BRT_END = 97,

	SGR_BG_BRT_START = 100,
	SGR_BG_BRT_END = 107,
};

#define SGR_OFF(n) (20+(n))

#endif //ESP_VT100_FIRMWARE_SGR_H
